// LocalizationMaps.tsx
// 251019 - 1st version with Gemini

import { CoreDefinitionKeys } from './CoreDefinitions';

export const languageVoc = {
	'en': 'english',
	'it': 'italiano',
}

// Tipo che definisce la Mappa di una lingua:
// Chiave: Nome visualizzato (es. "AVANTI" o "FORWARD")
// Valore: ID interno (es. "FD")
export type LanguageMap = Record<string, CoreDefinitionKeys>;

// Mappa per l'Italiano
export const IT_MAP: LanguageMap = {
  // Puoi includere sia i nomi abbreviati che quelli completi se vuoi
  "A": "FD",
  "AS": "MAKE",
  "ASCOLPENNA": "SETPENCOLOR",
  "ASSEGNA": "MAKE",
  "AVANTI": "FD",
  "COLORE": "PENCOLOR",
  "COLOREPENNA": "PENCOLOR",
  "COLPENNA": "PENCOLOR",
  "CONTA": "COUNT",
  "COSA": "THING",
  "D": "RT",
  "DACHELEGGI": "READER",
  "DESTRA": "RT",
  "DEFINISCI": "DEFINE",
  "DIFFERENZA": "DIFFERENCE",
  "DIMENSIONETARTARUGA": "TURTLESIZE",
  "ELE": "ITEM",
  "ELEMENTO": "ITEM",
  "FINE": "END",
  "FRASE": "SENTENCE",
  "GIU": "PENDOWN",
  "I": "BK",
  "INDIETRO": "BK",
  "INPRI": "FPUT",
  "INULT": "LPUT",
  "LISTA": "LIST",
  "LISTA?": "LISTP",
  "MAGGIORE?": "GREATERP",
  "MENO": "MINUS",
  "MENPRI": "BUTFIRST",
  "MENPRIMO": "BUTFIRST",
  "MENULT": "BUTLAST",
  "MENULTIMO": "BUTLAST",
  "MINORE?": "LESSP",
  "NON": "NOT",
  "NOT": "NOT",
  "NUMERO?": "NUMBERP",
  "PAROLA": "WORD",
  "PAROLA?": "WORDP",
  "PER": "TO",
  "POTENZA": "POWER",
  "PRI": "FIRST",
  "PRIMO": "FIRST",
  "PRODOTTO": "PRODUCT",
  "PS": "CS",
  "PULISCISCHERMO": "CS",
  "QUOTO": "INTEGER_QUOTIENT",
  "QUOZIENTE": "QUOTIENT",
  "RESTO": "REMAINDER",
  "RIPETI": "REPEAT",
  "SEGNO": "SIGN",
  "SOMMA": "SUM",
  "STAMPA": "PRINT",
  "UGUALE?": "EQUALP",
  "ULT": "LAST",
  "ULTIMO": "LAST",
  "SU": "PENUP",
  "SINISTRA": "LT",
  "S": "LT",
  "TANA": "HOME",
  "TESTO": "TEXT",

  "FALSO": "FALSE",
  "VERO": "TRUE",
};

// Mappa per l'Inglese
export const EN_MAP: LanguageMap = {
  "CLEARSCREEN": "CS",
  "CS": "CS",
  "HOME": "HOME",
  "PENUP": "PENUP",
  "PU": "PENUP",
  "PENDOWN": "PENDOWN",
  "PD": "PENDOWN",
  "FORWARD": "FD",
  "FD": "FD",
  "BACK": "BK",
  "BK": "BK",
  "RIGHT": "RT",
  "RT": "RT",
  "LEFT": "LT",
  "LT": "LT",
  "MAKE": "MAKE",
  "THING": "THING",
  "DEFINE": "DEFINE",
  "TO": "TO",
  "END": "END",
  "TEXT": "TEXT",
  "REPEAT": "REPEAT",
  "PRINT": "PRINT",
  "PENCOLOR": "PENCOLOR",
  "SETPENCOLOR": "SETPENCOLOR",
  "READER": "READER",
  "TURTLESIZE": "TURTLESIZE",
  "BUTFIRST": "BUTFIRST",
  "BF": "BUTFIRST",
  "BUTLAST": "BUTLAST",
  "BL": "BUTLAST",
  "COUNT": "COUNT",
  "DIFFERENCE": "DIFFERENCE",
  "EQUALP": "EQUALP",
  "FIRST": "FIRST",
  "FPUT": "FPUT",
  "GREATEREQUALP": "GREATEREQUALP",
  "GREATERP": "GREATERP",
  "INTEGER_QUOTIENT": "INTEGER_QUOTIENT",
  "ITEM": "ITEM",
  "LAST": "LAST",
  "LESSEQUALP": "LESSEQUALP",
  "LESSP": "LESSP",
  "LIST": "LIST",
  "LISTP": "LISTP",
  "LIST?": "LISTP",
  "LPUT": "LPUT",
  "MINUS": "MINUS",
  "NOT": "NOT",
  "NUMBERP": "NUMBERP",
  "NUMBER?": "NUMBERP",
  "POWER": "POWER",
  "PRODUCT": "PRODUCT",
  "QUOTIENT": "QUOTIENT",
  "REMAINDER": "REMAINDER",
  "SENTENCE": "SENTENCE",
  "SIGN": "SIGN",
  "SUM": "SUM",
  "WORD": "WORD",
  "WORDP": "WORDP",
  "WORD?": "WORDP",

  "FALSE": "FALSE",
  "TRUE": "TRUE",
};

export const LANGUAGE_MAPS: Record<string, LanguageMap> = {
  'it': IT_MAP,
  'en': EN_MAP,
  // ... altre lingue ...
};
